// ========= Copyright 2025-2026 @ Eigent.ai All Rights Reserved. =========
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ========= Copyright 2025-2026 @ Eigent.ai All Rights Reserved. =========

import { Provider } from '@/types';

export const INIT_PROVODERS: Provider[] = [
  {
    id: 'gemini',
    name: 'Gemini',
    apiKey: '',
    apiHost: 'https://generativelanguage.googleapis.com/v1beta/openai/',
    description: 'Google Gemini model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'gemini-3.1-pro-preview',
      'gemini-3-flash-preview',
      'gemini-3.1-flash-lite-preview',
      'gemini-2.5-pro',
      'gemini-2.5-flash',
      'gemini-2.5-flash-lite',
      'gemini-2.0-flash',
      'gemini-2.0-flash-lite',
    ],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    apiKey: '',
    apiHost: 'https://api.openai.com/v1',
    description: 'OpenAI model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'gpt-5.4',
      'gpt-5.4-mini',
      'gpt-5.4-nano',
      'gpt-5',
      'gpt-5-mini',
      'gpt-5-nano',
      'gpt-4.1',
      'gpt-4.1-mini',
      'gpt-4.1-nano',
      'o3',
      'o3-mini',
      'o4-mini',
      'gpt-4o',
      'gpt-4o-mini',
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    apiKey: '',
    apiHost: 'https://api.anthropic.com',
    description: 'Anthropic Claude API configuration',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'claude-opus-4-6',
      'claude-sonnet-4-6',
      'claude-opus-4-5-20251101',
      'claude-sonnet-4-5-20250929',
      'claude-opus-4-1-20250805',
      'claude-opus-4-20250514',
      'claude-sonnet-4-20250514',
      'claude-haiku-4-5-20251001',
    ],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    apiKey: '',
    apiHost: 'https://openrouter.ai/api/v1',
    description: 'OpenRouter model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'anthropic/claude-sonnet-4-6',
      'anthropic/claude-sonnet-4',
      'openai/gpt-5.4',
      'openai/gpt-5.4-mini',
      'openai/gpt-5.4-nano',
      'openai/gpt-4.1',
      'openai/o3',
      'openai/o4-mini',
      'google/gemini-3.1-pro-preview',
      'google/gemini-3-flash-preview',
      'google/gemini-2.5-pro',
      'google/gemini-2.5-flash',
      'deepseek/deepseek-v3.2',
      'deepseek/deepseek-r1',
      'minimax/minimax-m2.5',
      'meta-llama/llama-4-maverick',
      'mistralai/mistral-large',
      'qwen/qwen3-235b-a22b',
      'x-ai/grok-4',
    ],
  },
  {
    id: 'tongyi-qianwen',
    name: 'Qwen',
    apiKey: '',
    apiHost: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    description: 'Qwen model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'qwen-max',
      'qwen-plus',
      'qwen-turbo',
      'qwen3-235b-a22b',
      'qwen3-32b',
      'qwen3-14b',
      'qwen3-8b',
      'qwen3-4b',
      'qwen3-1.7b',
      'qwen3-0.6b',
      'qwq-plus',
    ],
  },
  {
    id: 'deepseek',
    name: 'Deepseek',
    apiKey: '',
    apiHost: 'https://api.deepseek.com',
    description: 'DeepSeek model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: ['deepseek-chat', 'deepseek-reasoner'],
  },
  {
    id: 'minimax',
    name: 'Minimax',
    apiKey: '',
    apiHost: 'https://api.minimax.io/v1',
    description: 'Minimax model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'MiniMax-M2.7',
      'MiniMax-M2.7-highspeed',
      'MiniMax-M2.5',
      'MiniMax-M2.5-highspeed',
      'MiniMax-M2.1',
      'MiniMax-M2.1-highspeed',
      'MiniMax-M2',
    ],
  },
  {
    id: 'z.ai',
    name: 'Z.ai',
    apiKey: '',
    apiHost: 'https://api.z.ai/api/coding/paas/v4/',
    description: 'Z.ai model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'glm-4.7',
      'glm-4.6',
      'glm-4-plus',
      'glm-4-flash',
      'glm-4',
    ],
  },
  {
    id: 'moonshot',
    name: 'Moonshot',
    apiKey: '',
    apiHost: 'https://api.moonshot.ai/v1',
    description: 'Kimi model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'kimi-k2.5',
      'kimi-k2',
      'moonshot-v1-128k',
      'moonshot-v1-32k',
      'moonshot-v1-8k',
    ],
  },
  {
    id: 'ModelArk',
    name: 'ModelArk',
    apiKey: '',
    apiHost: 'https://ark.ap-southeast.bytepluses.com/api/v3',
    description: 'ModelArk model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'doubao-seed-2.0-pro',
      'doubao-seed-2.0-lite',
      'doubao-seed-2.0-mini',
      'doubao-seed-2.0-code',
    ],
  },
  {
    id: 'samba-nova',
    name: 'SambaNova',
    apiKey: '',
    apiHost: 'https://api.sambanova.ai/v1',
    description: 'SambaNova model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'DeepSeek-V3.1',
      'DeepSeek-V3-0324',
      'DeepSeek-R1-0528',
      'DeepSeek-R1-Distill-Llama-70B',
      'Meta-Llama-3.3-70B-Instruct',
      'Meta-Llama-3.1-8B-Instruct',
      'Llama-4-Maverick-17B-128E-Instruct',
      'Llama-4-Scout-17B-16E-Instruct',
      'Qwen3-235B-A22B-Instruct-2507',
      'Qwen3-32B',
    ],
  },
  {
    id: 'grok',
    name: 'Grok',
    apiKey: '',
    apiHost: 'https://api.x.ai/v1',
    description: 'Grok model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'grok-4',
      'grok-3',
      'grok-3-mini',
      'grok-3-fast',
      'grok-code-fast-1',
      'grok-2',
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral',
    apiKey: '',
    apiHost: 'https://api.mistral.ai',
    description: 'Mistral model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'mistral-large-latest',
      'mistral-medium-latest',
      'mistral-small-latest',
      'codestral-latest',
      'devstral-latest',
      'ministral-8b-latest',
    ],
  },
  {
    id: 'aws-bedrock',
    name: 'AWS Bedrock',
    apiKey: '',
    apiHost: '',
    description: 'AWS Bedrock model configuration.',
    hostPlaceHolder: 'e.g. https://bedrock-runtime.{{region}}.amazonaws.com',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'anthropic.claude-opus-4-6-v1',
      'anthropic.claude-sonnet-4-6',
      'anthropic.claude-sonnet-4-5-20250929-v1:0',
      'anthropic.claude-sonnet-4-20250514-v1:0',
      'anthropic.claude-haiku-4-5-20251001-v1:0',
      'us.anthropic.claude-opus-4-6-v1',
      'us.anthropic.claude-sonnet-4-6',
      'us.meta.llama4-maverick-17b-instruct-v1:0',
      'us.meta.llama4-scout-17b-instruct-v1:0',
      'mistral.mistral-large-2407-v1:0',
    ],
  },
  {
    id: 'azure',
    name: 'Azure',
    apiKey: '',
    apiHost: '',
    description: 'Azure OpenAI model configuration.',
    hostPlaceHolder: 'e.g.https://{{your-resource-name}}.openai.azure.com',
    externalConfig: [
      {
        key: 'api_version',
        name: 'API Version',
        value: '',
      },
      {
        key: 'azure_deployment_name',
        name: 'Deployment Name',
        value: '',
      },
    ],
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'gpt-5.4',
      'gpt-5.4-mini',
      'gpt-5.4-nano',
      'gpt-5',
      'gpt-5-mini',
      'gpt-4.1',
      'gpt-4.1-mini',
      'gpt-4.1-nano',
      'gpt-4o',
      'gpt-4o-mini',
      'o3',
      'o4-mini',
    ],
  },
  {
    id: 'ernie',
    name: 'Ernie',
    apiKey: '',
    apiHost: 'https://qianfan.baidubce.com/v2',
    description: 'Baidu Ernie model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'ernie-5.0',
      'ernie-5.0-thinking-preview',
      'ernie-4.5-8k',
      'ernie-4.5-turbo-128k',
      'ernie-4.0-turbo-8k',
      'ernie-x1',
      'ernie-3.5-8k',
    ],
  },
  {
    id: 'openai-compatible-model',
    name: 'OpenAI Compatible',
    apiKey: '',
    apiHost: '',
    description: 'OpenAI-compatible API endpoint configuration.',
    hostPlaceHolder: 'e.g. https://api.x.ai/v1',
    is_valid: false,
    model_type: '',
    suggestedModels: [],
  },
];
