// ========= Copyright 2025-2026 @ Eigent.ai All Rights Reserved. =========
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ========= Copyright 2025-2026 @ Eigent.ai All Rights Reserved. =========

import { Provider } from '@/types';

export const INIT_PROVODERS: Provider[] = [
  {
    id: 'gemini',
    name: 'Gemini',
    apiKey: '',
    apiHost: 'https://generativelanguage.googleapis.com/v1beta/openai/',
    description: 'Google Gemini model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'gemini-2.5-pro-preview-06-05',
      'gemini-2.5-flash-preview-05-20',
      'gemini-2.0-flash',
      'gemini-2.0-flash-lite',
    ],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    apiKey: '',
    apiHost: 'https://api.openai.com/v1',
    description: 'OpenAI model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'gpt-4.1',
      'gpt-4.1-mini',
      'gpt-4.1-nano',
      'o3',
      'o4-mini',
      'gpt-4o',
      'gpt-4o-mini',
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    apiKey: '',
    apiHost: 'https://api.anthropic.com',
    description: 'Anthropic Claude API configuration',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'claude-opus-4-20250514',
      'claude-sonnet-4-20250514',
      'claude-3-7-sonnet-20250219',
      'claude-3-5-haiku-20241022',
    ],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    apiKey: '',
    apiHost: 'https://openrouter.ai/api/v1',
    description: 'OpenRouter model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [],
  },
  {
    id: 'tongyi-qianwen',
    name: 'Qwen',
    apiKey: '',
    apiHost: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    description: 'Qwen model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'qwen-max',
      'qwen-plus',
      'qwen-turbo',
      'qwen3-235b-a22b',
      'qwen3-32b',
    ],
  },
  {
    id: 'deepseek',
    name: 'Deepseek',
    apiKey: '',
    apiHost: 'https://api.deepseek.com',
    description: 'DeepSeek model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: ['deepseek-chat', 'deepseek-reasoner'],
  },
  {
    id: 'minimax',
    name: 'Minimax',
    apiKey: '',
    apiHost: 'https://api.minimax.io/v1',
    description: 'Minimax model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [],
  },
  {
    id: 'z.ai',
    name: 'Z.ai',
    apiKey: '',
    apiHost: 'https://api.z.ai/api/coding/paas/v4/',
    description: 'Z.ai model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: ['glm-4-plus', 'glm-4-flash', 'glm-4'],
  },
  {
    id: 'moonshot',
    name: 'Moonshot',
    apiKey: '',
    apiHost: 'https://api.moonshot.ai/v1',
    description: 'Kimi model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: ['moonshot-v1-128k', 'moonshot-v1-32k', 'moonshot-v1-8k'],
  },
  {
    id: 'ModelArk',
    name: 'ModelArk',
    apiKey: '',
    apiHost: 'https://ark.ap-southeast.bytepluses.com/api/v3',
    description: 'ModelArk model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [],
  },
  {
    id: 'samba-nova',
    name: 'SambaNova',
    apiKey: '',
    apiHost: 'https://api.sambanova.ai/v1',
    description: 'SambaNova model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [],
  },
  {
    id: 'grok',
    name: 'Grok',
    apiKey: '',
    apiHost: 'https://api.x.ai/v1',
    description: 'Grok model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: ['grok-3', 'grok-3-mini', 'grok-2'],
  },
  {
    id: 'mistral',
    name: 'Mistral',
    apiKey: '',
    apiHost: 'https://api.mistral.ai',
    description: 'Mistral model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: [
      'mistral-large-latest',
      'mistral-medium-latest',
      'mistral-small-latest',
      'codestral-latest',
    ],
  },
  {
    id: 'aws-bedrock',
    name: 'AWS Bedrock',
    apiKey: '',
    apiHost: '',
    description: 'AWS Bedrock model configuration.',
    hostPlaceHolder: 'e.g. https://bedrock-runtime.{{region}}.amazonaws.com',
    is_valid: false,
    model_type: '',
    suggestedModels: [],
  },
  {
    id: 'azure',
    name: 'Azure',
    apiKey: '',
    apiHost: '',
    description: 'Azure OpenAI model configuration.',
    hostPlaceHolder: 'e.g.https://{{your-resource-name}}.openai.azure.com',
    externalConfig: [
      {
        key: 'api_version',
        name: 'API Version',
        value: '',
      },
      {
        key: 'azure_deployment_name',
        name: 'Deployment Name',
        value: '',
      },
    ],
    is_valid: false,
    model_type: '',
    suggestedModels: [],
  },
  {
    id: 'ernie',
    name: 'Ernie',
    apiKey: '',
    apiHost: 'https://qianfan.baidubce.com/v2',
    description: 'Baidu Ernie model configuration.',
    is_valid: false,
    model_type: '',
    suggestedModels: ['ernie-4.5-8k', 'ernie-4.0-turbo-8k', 'ernie-3.5-8k'],
  },
  {
    id: 'openai-compatible-model',
    name: 'OpenAI Compatible',
    apiKey: '',
    apiHost: '',
    description: 'OpenAI-compatible API endpoint configuration.',
    hostPlaceHolder: 'e.g. https://api.x.ai/v1',
    is_valid: false,
    model_type: '',
    suggestedModels: [],
  },
];
