// ========= Copyright 2025-2026 @ Eigent.ai All Rights Reserved. =========
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ========= Copyright 2025-2026 @ Eigent.ai All Rights Reserved. =========

/**
 * Standalone entry for the public remote-control link route.
 *
 * Mounts only RemoteControlPage with the same theme/style provider stack used
 * by the designer web UI. It still avoids the logged-in app shell, query
 * client, host bridge, and dispatch workspace data flows.
 *
 * The public link page is served by this bundle in production (Nginx routes
 * `/remote-control/*` to `remote.html`); in dev, the Vite plugin in
 * `vite.config.ts` rewrites the same path. The full-app `index.html` retains
 * a fallback route so the page still works if a deployment forgets to wire
 * the path rewrite.
 */

import { ThemeProvider } from '@/components/layout/ThemeProvider';
import { TooltipProvider } from '@/components/ui/tooltip';
import '@fontsource/inter/400.css';
import '@fontsource/inter/500.css';
import '@fontsource/inter/600.css';
import '@fontsource/inter/700.css';
import { WebToaster } from '@web/components/layout/WebToaster';
import RemoteControlPage from '@web/pages/RemoteControlPage';
import '@web/styles.css';
import ReactDOM from 'react-dom/client';
import { BrowserRouter, Route, Routes } from 'react-router-dom';

function InvalidRemoteControlRoute() {
  return (
    <main className="text-white flex min-h-screen items-center justify-center bg-zinc-950 px-6">
      <section className="border-white/10 bg-white/[0.06] shadow-black/30 w-full max-w-md rounded-lg border p-6 shadow-2xl">
        <p className="text-xs font-semibold uppercase text-zinc-400">
          Eigent Remote Control
        </p>
        <h1 className="mt-3 text-xl font-semibold">
          Invalid remote control link
        </h1>
        <p className="mt-2 text-sm leading-6 text-zinc-300">
          Open the exact URL generated by the desktop app. If this link was
          copied manually, ask the desktop owner to generate a fresh one.
        </p>
      </section>
    </main>
  );
}

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <BrowserRouter>
    <ThemeProvider>
      <TooltipProvider>
        <Routes>
          <Route
            path="/remote-control/:sessionId"
            element={<RemoteControlPage />}
          />
          <Route path="*" element={<InvalidRemoteControlRoute />} />
        </Routes>
        <WebToaster />
      </TooltipProvider>
    </ThemeProvider>
  </BrowserRouter>
);
